### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by sxflynn** [SWHL/VideoOCR#4]
When I run the command

`
Looking in indexes: https://pypi.douban.com/simple/
Collecting rapidocr==1.0.0
  Using cached https://github.com/RapidAI/RapidOCR/raw/main/release/python_sdk/sdk_rapidocr_v1.0.0/rapidocr-1.0.0-py3-none-any.whl (18 kB)
ERROR: Could not find a version that satisfies the requirement onnxruntime>=1.7.0 (from rapidocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime>=1.7.0
`

However I have onnxruntime located here

`/opt/homebrew/Cellar/onnxruntime/1.9.1: 77 files, 11.9MB`

**Comment by glorious1** [comment]
@sxflynn Can you tell me why you closed this issue?  I'm having the same problem.

**Comment by sxflynn** [comment]
I closed it because it’s an issue for the RapidOCR project, not this one.
